from remerkleable.basic import uint as uint
from remerkleable.byte_arrays import Bytes32
from remerkleable.core import View
from typing import TypeVar

def serialize(obj: View) -> bytes: ...
def hash_tree_root(obj: View) -> Bytes32: ...
def uint_to_bytes(n: uint) -> bytes: ...
V = TypeVar('V', bound=View)

def copy(obj: V) -> V: ...
