phase0:
  - changed-files:
    - any-glob-to-any-file:
      - 'specs/phase0/**'
      - 'presets/*/phase0.yaml'
      - 'pysetup/spec_builders/phase0.py'

altair:
  - changed-files:
    - any-glob-to-any-file:
      - 'specs/altair/**'
      - 'presets/*/altair.yaml'
      - 'pysetup/spec_builders/altair.py'

bellatrix:
  - changed-files:
    - any-glob-to-any-file:
      - 'specs/bellatrix/**'
      - 'presets/*/bellatrix.yaml'
      - 'pysetup/spec_builders/bellatrix.py'

capella:
  - changed-files:
    - any-glob-to-any-file:
      - 'specs/capella/**'
      - 'presets/*/capella.yaml'
      - 'pysetup/spec_builders/capella.py'

deneb:
  - changed-files:
    - any-glob-to-any-file:
      - 'specs/deneb/**'
      - 'presets/*/deneb.yaml'
      - 'pysetup/spec_builders/deneb.py'

electra:
  - changed-files:
    - any-glob-to-any-file:
      - 'specs/electra/**'
      - 'presets/*/electra.yaml'
      - 'pysetup/spec_builders/electra.py'

fulu:
  - changed-files:
    - any-glob-to-any-file:
      - 'specs/fulu/**'
      - 'presets/*/fulu.yaml'
      - 'pysetup/spec_builders/fulu.py'

gloas:
  - changed-files:
    - any-glob-to-any-file:
      - 'specs/gloas/**'
      - 'presets/*/gloas.yaml'
      - 'pysetup/spec_builders/gloas.py'

eip6800:
  - changed-files:
    - any-glob-to-any-file:
      - 'specs/_features/eip6800/**'
      - 'presets/*/eip6800.yaml'
      - 'pysetup/spec_builders/eip6800.py'

eip6914:
  - changed-files:
    - any-glob-to-any-file:
      - 'specs/_features/eip6914/**'
      - 'presets/*/eip6914.yaml'
      - 'pysetup/spec_builders/eip6914.py'

eip7441:
  - changed-files:
    - any-glob-to-any-file:
      - 'specs/_features/eip7441/**'
      - 'presets/*/eip7441.yaml'
      - 'pysetup/spec_builders/eip7441.py'

eip7805:
  - changed-files:
    - any-glob-to-any-file:
      - 'specs/_features/eip7805/**'
      - 'presets/*/eip7805.yaml'
      - 'pysetup/spec_builders/eip7805.py'

eip7928:
  - changed-files:
    - any-glob-to-any-file:
      - 'specs/_features/eip7928/**'
      - 'presets/*/eip7928.yaml'
      - 'pysetup/spec_builders/eip7928.py'

eip8025:
  - changed-files:
    - any-glob-to-any-file:
      - 'specs/_features/eip8025/**'
      - 'presets/*/eip8025.yaml'
      - 'pysetup/spec_builders/eip8025.py'

eip8148:
  - changed-files:
    - any-glob-to-any-file:
      - 'specs/_features/eip8148/**'
      - 'presets/*/eip8148.yaml'
      - 'pysetup/spec_builders/eip8148.py'

testing:
  - changed-files:
    - any-glob-to-any-file:
      - 'tests/**'

ssz:
  - changed-files:
    - any-glob-to-any-file:
      - 'ssz/**'

lightclients:
  - changed-files:
    - any-glob-to-any-file:
      - 'specs/**/light-client/**'
