categories:
  # Forks
  - title: Phase0
    when:
      label: phase0
  - title: Altair
    when:
      label: altair
  - title: Bellatrix
    when:
      label: bellatrix
  - title: Capella
    when:
      label: capella
  - title: Deneb
    when:
      label: deneb
  - title: Electra
    when:
      label: electra
  - title: Fulu
    when:
      labels:
        - fulu
        - eip7594
  - title: Gloas
    when:
      labels:
        - gloas
        - eip7732
        - eip7843
        - eip7928
        - eip8061
  - title: Heze
    when:
      labels:
        - heze
        - eip7805

  # Features
  - title: EIP-6914
    when:
      label: eip6914
  - title: EIP-8025
    when:
      label: eip8025
  - title: EIP-8148
    when:
      label: eip8148

  # Testing
  - title: Testing
    when:
      label: testing

  # Dependencies
  - title: Dependencies
    when:
      label: dependencies

  # Fallback
  - title: Other

commitish: master
filter-by-commitish: true
include-pre-releases: true
sort-direction: ascending
change-title-escapes: '\<*_&'
change-template: '- $TITLE (#$NUMBER)'
template: |
  $CHANGES
