categories:
  # Forks
  - title: Phase0
    label: phase0
  - title: Altair
    label: altair
  - title: Bellatrix
    label: bellatrix
  - title: Capella
    label: capella
  - title: Deneb
    label: deneb
  - title: Electra
    label: electra
  - title: Fulu
    labels:
      - fulu
      - eip7594
  - title: Gloas
    labels:
      - gloas
      - eip7732
      - eip7843
      - eip7928

  # Features
  - title: EIP-6800
    label: eip6800
  - title: EIP-6914
    label: eip6914
  - title: EIP-7441
    label: eip7441
  - title: EIP-7805
    label: eip7805
  - title: EIP-7928
    label: eip7928
  - title: EIP-8025
    label: eip8025

  # Testing
  - title: Testing
    label: testing

  # Fallback
  - title: Other

commitish: master
filter-by-commitish: true
include-pre-releases: true
sort-direction: ascending
change-title-escapes: '\<*_&'
change-template: '- $TITLE (#$NUMBER)'
template: |
  $CHANGES
