"""Generate and validate state-transition compliance cases.

Usage:
    uv run python -m tests.generators.compliance_runners.state_transition.run
    uv run python -m tests.generators.compliance_runners.state_transition.run --handler withdrawals
    uv run python -m tests.generators.compliance_runners.state_transition.run --profile smoke
"""

from __future__ import annotations

import argparse
from importlib import import_module
from pathlib import Path
from types import SimpleNamespace
from typing import Any, TYPE_CHECKING

from eth_consensus_specs.gloas import minimal as spec

from .validation import HANDLERS, main as validate

if TYPE_CHECKING:
    from collections.abc import Callable

PROFILES = ("all", "smoke", "normal", "exceptional", "standard")


def materialize_profile(
    name: str,
    build_profile: Callable[[str], tuple[int, list[dict]]],
    materializer: Any,
    output_dir: Path | None = None,
):
    """Materialize a named handler coverage profile."""
    _, chosen = build_profile(name)
    reps = [SimpleNamespace(**record) for record in chosen]
    return materializer.materialize_reps(output_dir, reps)


def run(
    handler: str,
    comptests_output: Path | None = None,
    profile: str = "standard",
) -> int:
    handlers = HANDLERS if handler == "all" else (handler,)
    result = 0
    for current_handler in handlers:
        output_dir = (
            comptests_output
            if comptests_output is not None
            else Path(__file__).parent / current_handler / "reftests"
        )
        handler_module = import_module(f".{current_handler}", __package__)
        build_profile = handler_module.build_profile
        materializer = handler_module.MATERIALIZER(spec)
        print(f"Materializing '{profile}' test vectors for '{current_handler}'")
        materialize_profile(profile, build_profile, materializer, output_dir)
        print("Validating test vectors")
        # The output directory is shared when generating all handlers. Limit
        # validation to the handler just materialized; otherwise each pass
        # re-validates all handlers generated by earlier passes.
        result |= validate(output_dir, handlers=(current_handler,))
    return result


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--handler", choices=(*HANDLERS, "all"), default="all")
    parser.add_argument("--profile", choices=PROFILES, default="standard")
    parser.add_argument("--comptests-output", type=Path)
    args = parser.parse_args()
    return run(args.handler, args.comptests_output, args.profile)


if __name__ == "__main__":
    raise SystemExit(main())
