from remerkleable.core import BackedView as BackedView, BasicView as BasicView, View as View
from remerkleable.tree import Link as Link, to_gindex as to_gindex
from typing import Any, Type

class SubtreeView(BackedView):
    @classmethod
    def is_packed(cls: Any) -> bool: ...
    @classmethod
    def tree_depth(cls: Any) -> int: ...
    @classmethod
    def item_elem_cls(cls: Any, i: int) -> Type[View]: ...
    def get(self, i: int) -> View: ...
    def set(self, i: int, v: View) -> None: ...
