#!/usr/bin/env python3
"""
Remove the inline tables of contents from the copied documentation sources.

Every specification carries a table of contents generated by mdformat-toc, which
is what makes the documents navigable on GitHub. The documentation site renders
its own table of contents in the sidebar, so the inline one is redundant there.

The anchors in the inline tables of contents also use GitHub's convention for
duplicate headings, appending `-1`, `-2`, and so on, while Python-Markdown
appends `_1`, `_2`. Removing the inline tables of contents therefore drops the
only links that depend on that difference, and keeps the site free of links that
cannot resolve.

Only the copied documentation sources are modified. The specifications
themselves keep their tables of contents for readers on GitHub.
"""

import os
import sys

START_MARKER = "<!-- mdformat-toc start"
END_MARKER = "<!-- mdformat-toc end -->"


def strip_inline_toc(lines: list[str]) -> list[str] | None:
    """Return the lines without the table of contents, or None if there is none."""
    start = end = None
    for index, line in enumerate(lines):
        if start is None and line.startswith(START_MARKER):
            start = index
        elif line.startswith(END_MARKER):
            end = index
            break

    if start is None or end is None:
        return None

    return lines[:start] + lines[end + 1 :]


def main(docs_dir: str) -> None:
    """Remove the inline table of contents from every document."""
    print("Removing inline tables of contents...")

    if not os.path.isdir(docs_dir):
        print(f"error: docs directory does not exist: {docs_dir}")
        sys.exit(1)

    stripped = 0
    for root, _, files in os.walk(docs_dir):
        for file in sorted(files):
            if not file.endswith(".md"):
                continue

            path = os.path.join(root, file)
            with open(path) as f:
                lines = f.readlines()

            remaining = strip_inline_toc(lines)
            if remaining is None:
                continue

            with open(path, "w") as f:
                f.writelines(remaining)
            stripped += 1

    print(f"  - Removed the table of contents from {stripped} documents")


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else "docs")
