from __future__ import annotations

from collections.abc import Iterable
from pathlib import Path
from typing import Any, TypedDict

import _pytest
import pytest
from pytest import StashKey, TestReport

from eth_consensus_specs.test import context
from eth_consensus_specs.test.helpers.constants import TESTGEN_FORKS
from eth_consensus_specs.test.helpers.typing import SpecForkName
from tests.infra.dumper import Dumper
from tests.infra.manifest import Manifest
from tests.infra.yield_generator import MultiPhaseResult


class RunnerConfig(TypedDict, total=False):
    runner_name: str
    handler_name_fixed: str
    handler_name_map: dict[str, str]
    handler_name_strip: list[str]
    suite_name: str


RUNNERS: dict[str, RunnerConfig] = {
    # Simple runners: pkg == runner_name, default handler_name (strip "test_")
    "bls": {},
    "finality": {},
    "fork_choice": {},
    "fast_confirmation": {},
    "genesis": {},
    "kzg": {},
    "merkle_proof": {},
    "networking": {},
    "random": {},
    "rewards": {},
    "ssz_generic": {},
    "ssz_static": {},
    "sync": {},
    # Operations: path has "block_processing", runner is "operations"
    "block_processing": {
        "runner_name": "operations",
        "handler_name_map": {
            "test_process_sync_aggregate_random": "sync_aggregate",
        },
        "handler_name_strip": ["test_process_"],
    },
    # Epoch processing with custom handler derivation
    "epoch_processing": {
        "handler_name_map": {
            "test_apply_pending_deposit": "pending_deposits",
        },
        "handler_name_strip": ["test_process_", "test_apply_"],
    },
    # Sanity with special-case mappings
    "sanity": {
        "handler_name_map": {
            "test_deposit_transition": "blocks",
            "test_lookahead": "blocks",
            "test_lookahead_slots": "slots",
        },
    },
    # Light client
    "light_client": {
        "handler_name_map": {
            "test_sync_protocol": "sync",
        },
    },
    # Fork with fixed handler
    "fork": {
        "handler_name_fixed": "fork",
    },
    # Transition with fixed handler
    "transition": {
        "handler_name_fixed": "core",
    },
    # Shuffling with fixed handler and custom suite
    "shuffling": {
        "handler_name_fixed": "core",
        "suite_name": "shuffle",
    },
}


class SpecTestFunction(pytest.Function):
    """Custom pytest.Function subclass that captures test results.

    This class extends pytest.Function to store test vectors generated by
    spec tests, supporting both single-phase and multi-phase test results.

    Attributes:
        result: Test result data, either a list (single-phase) or a dict
                mapping fork names to lists (multi-phase)
    """

    result: MultiPhaseResult | list | None = None

    @classmethod
    def from_function(cls, f: pytest.Function) -> SpecTestFunction:
        """
        Create a SpecTestFunction from an existing pytest.Function.
        """
        self = cls.from_parent(
            parent=f.parent,
            name=f.name,
            callspec=getattr(f, "callspec", None),
            callobj=getattr(f, "_obj", _pytest.compat.NOTSET),
            keywords=f.keywords,
            fixtureinfo=getattr(f, "_fixtureinfo", None),
            originalname=f.originalname,
        )
        self._infer_manifest()

        return self

    @staticmethod
    def _find_runner(path: Path) -> tuple[str, RunnerConfig] | None:
        """Walk up parent directories to find the closest matching runner pkg.

        Skips unittests directories (not associated with generators).
        Returns (pkg_name, config) or None.
        """
        if "unittests" in path.parts:
            return None
        for parent in path.parents:
            if parent.name in RUNNERS:
                return parent.name, RUNNERS[parent.name]
        return None

    @staticmethod
    def _derive_handler_name(config: RunnerConfig, module_name: str) -> str:
        """Derive handler_name from runner config and module name."""
        if "handler_name_fixed" in config:
            return config["handler_name_fixed"]
        if module_name in config.get("handler_name_map", {}):
            return config["handler_name_map"][module_name]
        strips = config.get("handler_name_strip", ["test_"])
        handler_name = module_name
        for prefix in strips:
            handler_name = handler_name.removeprefix(prefix)
        return handler_name

    def _infer_manifest(self) -> None:
        """Infer manifest fields from the test's file path and runner config."""
        path = self.parent.path
        module_name = path.stem

        result = self._find_runner(path)
        if result is None:
            return
        pkg_name, config = result

        runner_name = config.get("runner_name", pkg_name)
        handler_name = self._derive_handler_name(config, module_name)
        suite_name = config.get("suite_name", getattr(self.obj, "suite_name", "pyspec_tests"))

        case_name = self.originalname or self.name
        if case_name.startswith("test_"):
            case_name = case_name[5:]

        preset = self.callspec.params.get("preset") if hasattr(self, "callspec") else None

        manifest = Manifest(
            runner_name=runner_name,
            handler_name=handler_name,
            case_name=case_name,
            suite_name=suite_name,
            preset_name=preset,
        )

        if hasattr(self.obj, "manifest") and self.obj.manifest is not None:
            manifest = self.obj.manifest.with_defaults(manifest)

        self.manifest = manifest

    def get_manifest(self) -> Manifest | None:
        if not hasattr(self, "manifest") or self.manifest is None:
            return None
        return self.manifest

    def get_result(self) -> MultiPhaseResult | list | None:
        return self.result


class YieldGeneratorPlugin:
    phase_report_key: StashKey[dict[str, TestReport]] = StashKey()

    def __init__(self, config):
        self.config = config
        self.output_dir: str = config.getoption("--reftests-output")
        self._dumper: Dumper | None = None

    @property
    def reftests_enabled(self) -> bool:
        return bool(self.config.getoption("--reftests"))

    @property
    def dumper(self) -> Dumper:
        if self._dumper is None:
            self._dumper = Dumper()
        return self._dumper

    def register(self):
        self.config.pluginmanager.register(self, "yield_generator")

    @staticmethod
    def _consume_result(result) -> MultiPhaseResult | list | None:
        """Consume the raw return value of a spec test function.

        Handles three cases:
        - dict: multi-phase result; each value is eagerly consumed, with
          per-phase skips caught so other phases still produce vectors.
        - Iterable: single-phase generator result, consumed into a list.
        - Other: returned as-is.
        """
        if result is None:
            return None

        if isinstance(result, dict):
            consumed: dict = {}
            last_skipped: BaseException | None = None
            for k, v in result.items():
                if v is None:
                    continue
                try:
                    consumed[k] = list(v)
                except _pytest.outcomes.Skipped as exc:
                    last_skipped = exc
                    continue
            if consumed:
                return consumed
            elif last_skipped is not None:
                raise last_skipped
            return None

        if isinstance(result, Iterable):
            return list(result)

        return result

    @pytest.hookimpl(tryfirst=True)
    def pytest_pyfunc_call(self, pyfuncitem: pytest.Function):
        if not isinstance(pyfuncitem, SpecTestFunction):
            return None

        pyfuncitem.result = None

        testfunction = pyfuncitem.obj
        if _pytest.compat.is_async_function(testfunction):
            _pytest.compat.async_fail(pyfuncitem.nodeid)
        funcargs = pyfuncitem.funcargs
        testargs = {arg: funcargs[arg] for arg in pyfuncitem._fixtureinfo.argnames}
        result = testfunction(**testargs)
        if hasattr(result, "__await__") or hasattr(result, "__aiter__"):
            _pytest.compat.async_fail(pyfuncitem.nodeid)

        pyfuncitem.result = self._consume_result(result)
        return True

    @pytest.hookimpl(wrapper=True, tryfirst=True)
    def pytest_runtest_makereport(self, item, call):
        rep = yield
        item.stash.setdefault(self.phase_report_key, {})[rep.when] = rep
        return rep

    def _should_generate(self, item) -> bool:
        """Check whether a test vector should be generated for this item."""
        if not self.reftests_enabled:
            return False
        if not isinstance(item, SpecTestFunction):
            return False
        reports = item.stash.get(self.phase_report_key, {})
        return not any(
            reports.get(phase) is not None and reports[phase].skipped for phase in ("setup", "call")
        )

    @pytest.hookimpl(hookwrapper=True)
    def pytest_runtest_protocol(self, item, nextitem):
        yield

        if not self._should_generate(item):
            return

        manifest = item.get_manifest()
        result = item.get_result()

        if manifest is not None and result is None:
            item.warn(pytest.PytestWarning(f"manifest but vector not created for {item.name}"))

        if manifest is not None and result is not None:
            self.generate_test_vector(manifest, result)

    def pytest_collection_modifyitems(self, config, items):
        if not self.reftests_enabled:
            return

        for i, item in enumerate(items):
            if isinstance(item, pytest.Function):
                items[i] = SpecTestFunction.from_function(item)

    def pytest_configure(self, config):
        if self.reftests_enabled:
            context.is_pytest = True
            context.is_generator = True
            # Limit to TESTGEN_FORKS so experimental forks (eip7928, eip8025)
            # don't produce output that the old generator wouldn't produce.
            context.DEFAULT_PYTEST_FORKS = set(TESTGEN_FORKS)

    @staticmethod
    def _resolve_fork_name(
        manifest: Manifest, phase_result: list, default: SpecForkName
    ) -> SpecForkName:
        """Resolve fork name from manifest or yielded metadata.

        For fork/transition tests the run phase is the pre-fork but the output
        should be placed under the post-fork directory.
        """
        if manifest.fork_name is not None:
            return default
        for name, kind, data in phase_result:
            if kind == "meta" and name in ("fork", "post_fork"):
                return data
        return default

    def generate_test_vector(self, manifest: Manifest, result: MultiPhaseResult | list) -> None:
        if isinstance(result, dict):
            for fork_name, phase_result in result.items():
                resolved_fork = self._resolve_fork_name(manifest, phase_result, fork_name)
                self._dump_phase(manifest, phase_result, resolved_fork)
        else:
            assert manifest.fork_name is not None, (
                f"fork_name must be set for single-phase test: {manifest}"
            )
            self._dump_phase(manifest, result, manifest.fork_name)

    def _dump_phase(self, manifest: Manifest, phase_result: list, fork_name: SpecForkName) -> None:
        """Write a single phase's test vector to disk."""
        manifest = manifest.with_defaults(Manifest(fork_name=fork_name))
        assert manifest.is_complete(), (
            f"Manifest must be complete to generate test vector for {manifest}"
        )

        output_dir = (
            Path(self.output_dir)
            / manifest.preset_name  # type: ignore
            / manifest.fork_name
            / manifest.runner_name
            / manifest.handler_name
            / manifest.suite_name
            / manifest.case_name
        )

        outputs: list[tuple[str, Any, Any]] = []
        meta: dict[str, Any] = {}

        for name, kind, data in phase_result:
            if kind == "meta":
                meta[name] = data
            else:
                method = getattr(self.dumper, f"dump_{kind}", None)
                if method is None:
                    raise ValueError(f"Unknown kind {kind!r}")
                outputs.append((name, method, data))

        for name, method, data in outputs:
            method(output_dir, name, data)

        if meta:
            self.dumper.dump_meta(output_dir, meta)

        self.dumper.dump_manifest(
            output_dir,
            {
                "preset": manifest.preset_name,
                "fork": manifest.fork_name,
                "runner": manifest.runner_name,
                "handler": manifest.handler_name,
                "suite": manifest.suite_name,
                "case": manifest.case_name,
            },
        )


def pytest_addoption(parser):
    """Add custom command-line options"""
    parser.addoption(
        "--reftests", action="store_true", default=False, help="Generate reference tests"
    )
    parser.addoption(
        "--reftests-output",
        default="reftests",
        help="Output directory for reference tests",
    )


def pytest_configure(config):
    """Register the plugin only when --reftests is enabled."""
    if config.getoption("--reftests", default=False):
        YieldGeneratorPlugin(config).register()
