name: Check Gnosis Sync

on:
  pull_request:
  schedule:
    - cron: '0 */4 * * *'

jobs:
  check-sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - name: Check gnosis preset/config is synced with gnosischain/specs
      run: bash scripts/check_gnosis_sync.sh
