name: Close Stale Issues and PRs

on:
  schedule:
    # Every day at 00:00 UTC
    - cron: '0 0 * * *'

jobs:
  stale:
    runs-on: [self-hosted-ghr-custom, size-s-x64, profile-consensusSpecs]
    permissions:
      actions: write
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@997185467fa4f803885201cee163a9f38240193d # v10.1.1
        with:
          days-before-stale: 365
          days-before-close: 30
          stale-issue-label: stale
          stale-pr-label: stale
          stale-issue-message: |
            This issue has been inactive for one year.
            Marking as stale.
            It will be closed after another 30 days of inactivity.
          stale-pr-message: |
            This PR has been inactive for one year.
            Marking as stale.
            It will be closed after another 30 days of inactivity.
